### ISSUE TITLE
export database

### ISSUE THREAD

**Issue by desdulianto** [mario34105/WebProgrammingPHP#1]
tolong export database supaya saya bisa cek webnya

**Comment by mario34105** [comment]
export gmn ya sir maksudnya?

export jdi .sql ?

**Comment by desdulianto** [comment]
Iya mario, karena kalo g ada sqlnya saya ga bisa jalankan web nya.

**Comment by mario34105** [comment]
ini ya sir filenya

**Comment by desdulianto** [comment]
eh mana mario? kirim lewat mana? kalau bisa push ke github nya aja sih

**Comment by mario34105** [comment]
aku kirim ke email sir tdi di attachment

**Comment by mario34105** [comment]
oke sir aku push ya

**Comment by desdulianto** [comment]
ok
